### ISSUE TITLE
Short-term multiplier not correctly implemented

### ISSUE THREAD

**Issue by Heisenberg32** [Natsiopoulos/ARDL#11]
Hi, the impact multiplier is different for the ARDL and the resulting ECM model which should not be the case. Please check that code!

**Comment by Natsiopoulos** [comment]
Hi, could you please send a reprex?
I tried to reproduce what you described but everything seems fine.

**Comment by Natsiopoulos** [comment]
Hi, the short-run multipliers were falsely weighted by the adjustment coefficient like in the case of the long-run multipliers.
This is fixed in commit https://github.com/Natsiopoulos/ARDL/commit/039efe66b59b457fabcb54f7c0508642ec9dac41.
