### ISSUE TITLE
Error with bounds_f_test

### ISSUE THREAD

**Issue by mabuimo** [Natsiopoulos/ARDL#12]
bounds_f_test(ardl_2421, case = 2)
Error in qr.solve(L %% V %% t(L)) : singular matrix 'a' in solve

Do you have any thoughts about this error? thank you

**Comment by Natsiopoulos** [comment]
Hi, could you please send a reprex?
`qr.solve` is part of base R involved in regression model estimation, so I believe the problem is with the definition of the model.
