### ISSUE TITLE
Is it possible to get standard errors for the delay multipliers?

### ISSUE THREAD

**Issue by sammy-w** [Natsiopoulos/ARDL#17]
Hello,

First of all, thank you for your amazing package. I am currently using it in my research, and I will cite it. 
I'm trying to create an IRF using the delay multipliers, but I don't see how I can get the standard errors of the delay multipliers.
Is this possible with the current package? If not, could this be implemented? 
Thank you in advance for any help you may offer.

**Comment by Natsiopoulos** [comment]
Thank you for the suggestion. It's done in #d0466c7
Let me know what you think about the implementation.

**Comment by sammy-w** [comment]
Hi Kleanthis,

Thank you very much for implementing this! Upon first glance, it looks good to me but I am not an expert on time series analysis.
I am at a conference in the USA, but I will forward it to my supervisor (Ines wilms) who is an expert on this to check it.
I'll let you know what she thinks, but I expect that she will agree that it is a good implementation.
She also checked the code for the delay multipliers and so on, and she found that everything was okay.
Thank you very much again, and good luck with your research!

Best,

Sammy Wals

________________________________
Van: Kleanthis Natsiopoulos ***@***.***>
Verzonden: dinsdag 16 mei 2023 13:19
Aan: Natsiopoulos/ARDL ***@***.***>
CC: sammy-w ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Natsiopoulos/ARDL] Is it possible to get standard errors for the delay multipliers? (Issue #17)


Thank you for the suggestion. It's done in #d0466c7
Let me know what you think about the implementation.

**Comment by sammy-w** [comment]
Hi Kleanthis,

My supervisor did a couple of quick checks and she found no issues. 
Thank you very much again for implementing this functionality.

Best,

Sammy Wals
