### ISSUE TITLE
coint_eq() 

### ISSUE THREAD

**Issue by jngwj** [Natsiopoulos/ARDL#18]
It seems that coint_eq() returns a time series instead of a cointegrating vector. Using the example in the vignette also returns a time series instead of a cointegrating vector. Possible error? thank you.

**Comment by Natsiopoulos** [comment]
This is what `coint_eq()` is supposed to return. The cointegrating series, which is the long-run relationship.
From the `coint_eq()` function in the manual:

> Creates the cointegrating equation (long-run level relationship) providing an ’ardl’, ’uecm’ or ’recm’
model.

> `coint_eq` returns a numeric vector containing the cointegrating equation.

If you are interested in the cointegrating vector, the coefficients that create the prementioned long-run relationship, these are provided by the `multipliers` function.
