### ISSUE TITLE
Using AutoARDL() with exogenous variables 

### ISSUE THREAD

**Issue by omzeybek** [Natsiopoulos/ARDL#3]
Hi I am using ARDL package with a time series data with 150 variables,  which I assume 90 of them have dynamic character and others are exogenous dummy variables. But I need to add exo variables to my equation. Following documentation on CRAN, I wrote a code given below; 

models <- auto_ardl(x~ y | exo_var , data=dfzooreg, max_order = 5)

but estimation cannot include the exo_var to the model. Am I doing the wrong way to add exo variables?

**Comment by Natsiopoulos** [comment]
Hello.
No, you do it the right way.
Just to clarify, in your example `models <- auto_ardl(x~ y | exo_var , data=dfzooreg, max_order = 5)` you realize that you are using just one independent variable (y) and one exogenus (exo_var), right?
If so, yes this is indeed the right paradigm of how to use it.

The first things you can try are:
- Can you successfully run the following? It is the example in the help file of ardl() but customized to run in the auto_ardl() function. This is to confirm that the function generally runs at your system.
`data(denmark)`
`d_74Q1_75Q3_ <- ifelse(time(denmark) >= "1974 Q1" & time(denmark) <= "1975 Q3", 1, 0)`
`den <- cbind(denmark, d_74Q1_75Q3)`
`ardl_3132_d <- auto_ardl(LRM ~ LRY + IBO + IDE | d_74Q1_75Q3, data = den, max_order = 3)`

- Assuming that it does, I would run the same model using a subset of the dataset, just in case.

It would be much more helpful if you could explain what exactly is the problem?
Is there an error message, if yes what is it?
Does the model run but it just ignores the exogenous variables?

If you still face this problem, can you attach a small sample of your data (or sent it via email) so I can try to reproduce the problem?

Thank you.
